name: Build Base Blender Image

on:
  workflow_dispatch:
    inputs:
      blender_version:
        description: 'Blender version to install'
        required: true
        default: '4.3.0'
        type: string
      tag_version:
        description: 'Tag version for the base image'
        required: true
        default: 'latest'
        type: string

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update Dockerfile with Blender version
      run: |
        # Update the Dockerfile.blender with the specified Blender version
        BLENDER_VERSION="${{ inputs.blender_version }}"
        sed -i "s/blender-[0-9]\+\.[0-9]\+\.[0-9]\+/blender-${BLENDER_VERSION}/g" Dockerfile.blender
        sed -i "s/Blender[0-9]\+\.[0-9]\+/Blender$(echo ${BLENDER_VERSION} | cut -d. -f1-2)/g" Dockerfile.blender
        echo "Updated Dockerfile.blender to use Blender ${BLENDER_VERSION}"

    - name: Build and push base Blender image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: iwatkot/blender:${{ inputs.tag_version }}
        file: ./Dockerfile.blender

    - name: Test base image
      run: |
        docker run --rm iwatkot/blender:${{ inputs.tag_version }} blender --version

    - name: Summary
      run: |
        echo "## 🎨 Base Blender Image Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Image:** \`iwatkot/blender:${{ inputs.tag_version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Blender Version:** \`${{ inputs.blender_version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Size:** Run \`docker images iwatkot/blender:${{ inputs.tag_version }}\` to check size" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🚀 Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "- Update your main applications to use this base image" >> $GITHUB_STEP_SUMMARY
        echo "- This base image includes Blender ${{ inputs.blender_version }} and all dependencies" >> $GITHUB_STEP_SUMMARY
        echo "- Main app builds will now be much faster!" >> $GITHUB_STEP_SUMMARY
